# Generated by Django 5.1.7 on 2025-04-09 23:45

import webapp.viewer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_rename_streamhighlights_streamhighlight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='stream',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=webapp.viewer.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
