# Generated by Django 5.2 on 2025-04-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_delete_user_stream_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='analysis_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('ERROR', 'Error')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='stream',
            name='avg_loudness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='max_loudness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='p90_loudness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='sound_csv_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='streamhighlight',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
