# Generated by Django 5.2 on 2025-04-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_stream_analysis_status_stream_avg_loudness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='analysis_status',
            field=models.CharField(choices=[('PENDING', 'Ausstehend'), ('PROCESSING', 'In Arbeit'), ('COMPLETE', 'Abgeschlossen'), ('ERROR', 'Fehler')], default='PENDING', max_length=20),
        ),
    ]
